# Generated by Django 5.2.10 on 2026-02-01 06:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='core_blogpo_slug_36a1f7_idx'), models.Index(fields=['is_published'], name='core_blogpo_is_publ_bed51c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('STUDIO', 'Studio'), ('PG', 'PG/Hostel'), ('TOWNHOUSE', 'Townhouse'), ('OTHER', 'Other')], default='APARTMENT', max_length=30)),
                ('room_type', models.CharField(choices=[('PRIVATE', 'Private Room'), ('SHARED', 'Shared Room'), ('ENTIRE', 'Entire Unit')], default='ENTIRE', max_length=30)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('area_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('rent_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maintenance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bills_included', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended'), ('RENTED', 'Rented')], default='DRAFT', max_length=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('min_stay_months', models.PositiveIntegerField(default=1)),
                ('max_stay_months', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(default='India', max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('locality', models.CharField(blank=True, max_length=140)),
                ('address_line1', models.CharField(blank=True, max_length=240)),
                ('address_line2', models.CharField(blank=True, max_length=240)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_pin_verified', models.BooleanField(default=False)),
                ('furnish_status', models.CharField(choices=[('UNFURNISHED', 'Unfurnished'), ('SEMI', 'Semi-Furnished'), ('FULL', 'Fully Furnished')], default='SEMI', max_length=20)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_lift', models.BooleanField(default=False)),
                ('has_power_backup', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_washing_machine', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('alcohol_allowed', models.BooleanField(default=False)),
                ('guests_allowed', models.BooleanField(default=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('featured_video_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('priority_rank', models.PositiveIntegerField(default=0)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='core_proper_status_95c99c_idx'), models.Index(fields=['city'], name='core_proper_city_d99175_idx'), models.Index(fields=['locality'], name='core_proper_localit_2675ca_idx'), models.Index(fields=['rent_monthly'], name='core_proper_rent_mo_3be6ef_idx'), models.Index(fields=['property_type'], name='core_proper_propert_858877_idx'), models.Index(fields=['room_type'], name='core_proper_room_ty_a0cb50_idx'), models.Index(fields=['is_featured'], name='core_proper_is_feat_09dca4_idx'), models.Index(fields=['priority_rank'], name='core_proper_priorit_2f0bbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('is_cover', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'sort_order'], name='core_proper_propert_16ad9d_idx'), models.Index(fields=['property', 'is_cover'], name='core_proper_propert_7a5755_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('VIMEO', 'Vimeo'), ('MP4', 'Direct MP4'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.property')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'sort_order'], name='core_proper_propert_ddbe98_idx'), models.Index(fields=['property', 'is_featured'], name='core_proper_propert_8aac60_idx'), models.Index(fields=['provider'], name='core_proper_provide_90d1d8_idx')],
            },
        ),
    ]
