# Generated by Django 5.2.7 on 2026-02-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('landlord', 'Landlord'), ('tenant', 'Tenant'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['contact_type'], name='core_contac_contact_3e3796_idx'),
        ),
    ]
