# Generated by Django 5.2.10 on 2026-05-05 09:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage_contact_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntentForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity', models.CharField(choices=[('STUDENT', 'Student'), ('WORKING', 'Working Professional'), ('COUPLE', 'Couple')], default='STUDENT', max_length=30)),
                ('purpose', models.CharField(choices=[('STUDY', 'Study'), ('WORK', 'Work'), ('BOTH', 'Both'), ('SHORT_STAY', 'Short-term Stay')], default='STUDY', max_length=30)),
                ('room_type', models.CharField(max_length=80)),
                ('budget_min', models.PositiveIntegerField(default=0)),
                ('budget_max', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(max_length=120)),
                ('preferred_locality', models.CharField(blank=True, max_length=160)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('visa_type', models.CharField(blank=True, max_length=80)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('proof_of_funds_verified', models.BooleanField(default=False)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('lifestyle_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ISRAscore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stability_score', models.PositiveIntegerField(default=0)),
                ('financial_score', models.PositiveIntegerField(default=0)),
                ('behavioural_score', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('risk_band', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='HIGH', max_length=20)),
                ('recommended_max_rent', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('override_applied', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ISRA score',
                'verbose_name_plural': 'ISRA scores',
            },
        ),
        migrations.CreateModel(
            name='PropertyExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('RENOVATION', 'Renovation'), ('FURNITURE', 'Furniture'), ('REPAIRS', 'Repairs'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('incurred_on', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PropMatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('budget_pass', models.BooleanField(default=False)),
                ('availability_pass', models.BooleanField(default=False)),
                ('isra_pass', models.BooleanField(default=False)),
                ('eligible', models.BooleanField(default=False)),
                ('rationale', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['rank', '-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='RentLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utility_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='DUE', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('deposit_status', models.CharField(blank=True, max_length=80)),
                ('extension_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='assigned_landlord',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'LANDLORD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='isra_threshold',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['assigned_landlord'], name='core_proper_assigne_9eafb1_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.property'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intentform',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intent_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='israscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isra_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyexpense',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyexpense',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.property'),
        ),
        migrations.AddField(
            model_name='propmatchresult',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_matches', to='core.property'),
        ),
        migrations.AddField(
            model_name='propmatchresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='core.property'),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentledger',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_ledger', to='core.tenancy'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='core_compla_status_5d4f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['property', 'status'], name='core_compla_propert_5465a9_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='core_compla_created_f58568_idx'),
        ),
        migrations.AddIndex(
            model_name='intentform',
            index=models.Index(fields=['city'], name='core_intent_city_fd1fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='intentform',
            index=models.Index(fields=['budget_max'], name='core_intent_budget__6dd650_idx'),
        ),
        migrations.AddIndex(
            model_name='intentform',
            index=models.Index(fields=['created_at'], name='core_intent_created_280f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='israscore',
            index=models.Index(fields=['total_score'], name='core_israsc_total_s_0bca2e_idx'),
        ),
        migrations.AddIndex(
            model_name='israscore',
            index=models.Index(fields=['risk_band'], name='core_israsc_risk_ba_9a0300_idx'),
        ),
        migrations.AddIndex(
            model_name='israscore',
            index=models.Index(fields=['calculated_at'], name='core_israsc_calcula_5efd03_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyexpense',
            index=models.Index(fields=['property', 'category'], name='core_proper_propert_e45877_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyexpense',
            index=models.Index(fields=['landlord'], name='core_proper_landlor_a3ab49_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyexpense',
            index=models.Index(fields=['incurred_on'], name='core_proper_incurre_08a761_idx'),
        ),
        migrations.AddIndex(
            model_name='propmatchresult',
            index=models.Index(fields=['user', 'rank'], name='core_propma_user_id_65fb44_idx'),
        ),
        migrations.AddIndex(
            model_name='propmatchresult',
            index=models.Index(fields=['eligible'], name='core_propma_eligibl_0eab8f_idx'),
        ),
        migrations.AddIndex(
            model_name='propmatchresult',
            index=models.Index(fields=['generated_at'], name='core_propma_generat_22a0b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propmatchresult',
            unique_together={('user', 'property')},
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['user', 'status'], name='core_tenanc_user_id_2479c1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['property', 'status'], name='core_tenanc_propert_1358c1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['start_date'], name='core_tenanc_start_d_a20989_idx'),
        ),
        migrations.AddIndex(
            model_name='rentledger',
            index=models.Index(fields=['due_date'], name='core_rentle_due_dat_b87d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='rentledger',
            index=models.Index(fields=['status'], name='core_rentle_status_82ab28_idx'),
        ),
    ]
