# Generated by Django 5.2.10 on 2026-05-05 16:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_complaint_intentform_israscore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YOEMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gross_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('net_yield', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rent_collection_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active_tenancies', models.PositiveIntegerField(default=0)),
                ('open_complaints', models.PositiveIntegerField(default=0)),
                ('recommendation', models.CharField(blank=True, max_length=240)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yoe_metrics', to=settings.AUTH_USER_MODEL)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yoe_metric', to='core.property')),
            ],
            options={
                'verbose_name': 'YOE metric',
                'verbose_name_plural': 'YOE metrics',
                'indexes': [models.Index(fields=['landlord'], name='core_yoemet_landlor_39fdc6_idx'), models.Index(fields=['net_yield'], name='core_yoemet_net_yie_8a56e1_idx'), models.Index(fields=['calculated_at'], name='core_yoemet_calcula_6e9c49_idx')],
            },
        ),
    ]
