# Generated by Django 5.2.10 on 2026-05-05 17:22

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_yoemetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=core.models.private_complaint_attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.complaint')),
            ],
            options={
                'indexes': [models.Index(fields=['complaint'], name='core_compla_complai_18ccd1_idx'), models.Index(fields=['uploaded_at'], name='core_compla_uploade_06fcbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('VISA', 'Visa'), ('PROOF_OF_FUNDS', 'Proof of Funds'), ('UNIVERSITY_CERTIFICATE', 'University Certificate'), ('IDENTITY', 'Identity'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('file', models.FileField(upload_to=core.models.private_document_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'document_type'], name='core_studen_user_id_55d704_idx'), models.Index(fields=['verification_status'], name='core_studen_verific_9bd52c_idx'), models.Index(fields=['uploaded_at'], name='core_studen_uploade_a6f545_idx')],
            },
        ),
    ]
