# Generated by Django 5.2.10 on 2026-05-06 04:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_complaintattachment_studentdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenancyHealthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('RENT_PAID_ON_TIME', 'Rent Paid On Time'), ('RENT_LATE', 'Rent Late'), ('COMPLAINT_RAISED', 'Complaint Raised'), ('COMPLAINT_RESOLVED', 'Complaint Resolved'), ('ADMIN_NOTE', 'Admin Note')], max_length=40)),
                ('weight', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='core.tenancy')),
            ],
            options={
                'indexes': [models.Index(fields=['tenancy', 'occurred_at'], name='core_tenanc_tenancy_1b2fe0_idx'), models.Index(fields=['event_type'], name='core_tenanc_event_t_51f0b1_idx')],
                'unique_together': {('source_type', 'source_id', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='TenancyHealthScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=70)),
                ('band', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('rent_signal', models.PositiveIntegerField(default=70)),
                ('complaint_signal', models.PositiveIntegerField(default=70)),
                ('communication_signal', models.PositiveIntegerField(default=70)),
                ('trend', models.CharField(default='STABLE', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_score', to='core.tenancy')),
            ],
            options={
                'indexes': [models.Index(fields=['score'], name='core_tenanc_score_93057e_idx'), models.Index(fields=['band'], name='core_tenanc_band_13f2bb_idx'), models.Index(fields=['calculated_at'], name='core_tenanc_calcula_247e90_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenancyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_label', models.CharField(default='Verified Tenant', max_length=120)),
                ('outcome', models.CharField(default='Completed Successfully', max_length=120)),
                ('ths_score_snapshot', models.PositiveIntegerField(default=0)),
                ('certificate_code', models.CharField(max_length=40, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancy_records', to='core.property')),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portable_record', to='core.tenancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'issued_at'], name='core_tenanc_user_id_201ae5_idx'), models.Index(fields=['certificate_code'], name='core_tenanc_certifi_4df116_idx')],
            },
        ),
    ]
