# Generated by Django 5.2.7 on 2026-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenancyhealthevent_tenancyhealthscore_tenancyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancyhealthscore',
            name='policy_version',
            field=models.CharField(default='THS-Y1-1', max_length=20),
        ),
        migrations.AddField(
            model_name='tenancyhealthscore',
            name='reason_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
