# Generated by Django 5.2.10 on 2026-05-28 16:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenancyhealthscore_policy_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('APPLICATION', 'Application'), ('VERIFICATION', 'Verification'), ('MATCHING', 'Matching'), ('MOVE_IN', 'Move-in'), ('CARE', 'Care'), ('SUPPORT', 'Support'), ('RENEWAL', 'Renewal'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='APPLICATION', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('stage_notes', models.CharField(blank=True, max_length=240)),
                ('next_action', models.CharField(blank=True, max_length=240)),
                ('target_move_in_date', models.DateField(blank=True, null=True)),
                ('stage_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prop_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_applications', to='core.propmatchresult')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_applications', to='core.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'stage'], name='core_housin_user_id_83cc9c_idx'), models.Index(fields=['property', 'stage'], name='core_housin_propert_37e9c1_idx'), models.Index(fields=['status'], name='core_housin_status_bb1913_idx'), models.Index(fields=['updated_at'], name='core_housin_updated_98916e_idx')],
            },
        ),
    ]
