# Generated by Django 5.2.10 on 2026-05-29 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_studentdocument_reviewed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='housingapplication',
            name='admin_entry_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='applicant_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='application_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='entry_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='entry_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('RETURNED', 'Returned for Update'), ('READY', 'Ready for Verification')], default='SUBMITTED', max_length=30),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='intake_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='intake_source',
            field=models.CharField(choices=[('STUDENT_PORTAL', 'Student Portal'), ('ADMIN_CREATED', 'Admin Created'), ('PROPMATCH_LOCK', 'PropMatch Lock'), ('CONTACT_CONVERSION', 'Contact Conversion')], default='STUDENT_PORTAL', max_length=30),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='housingapplication',
            index=models.Index(fields=['entry_status'], name='core_housin_entry_s_c61d04_idx'),
        ),
        migrations.AddIndex(
            model_name='housingapplication',
            index=models.Index(fields=['intake_source'], name='core_housin_intake__359877_idx'),
        ),
    ]
