# Generated by Django 5.2.10 on 2026-05-29 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_housingapplication_admin_entry_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_documents', to='core.housingapplication'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='requirement_stage',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('VERIFICATION', 'Verification'), ('MOVE_IN', 'Move-in')], default='VERIFICATION', max_length=30),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='resubmission_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='student_message',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('VISA', 'Visa'), ('PROOF_OF_FUNDS', 'Proof of Funds'), ('UNIVERSITY_CERTIFICATE', 'University Certificate'), ('IDENTITY', 'Identity'), ('PASSPORT', 'Passport'), ('RIGHT_TO_RENT', 'Right to Rent'), ('GUARANTOR_OR_SPONSOR', 'Guarantor or Sponsor Letter'), ('ADDRESS_HISTORY', 'Address History'), ('EMERGENCY_CONTACT', 'Emergency Contact'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMISSION_REQUIRED', 'Resubmission Required'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['application', 'document_type'], name='core_studen_applica_0abe21_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['requirement_stage'], name='core_studen_require_cdf404_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['expiry_date'], name='core_studen_expiry__89416a_idx'),
        ),
    ]
