# Generated by Django 5.2.10 on 2026-05-29 17:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentdocument_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropMatchScoreHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('rule_version', models.CharField(default='QM-Y1-1', max_length=30)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('eligible', models.BooleanField(default=False)),
                ('budget_pass', models.BooleanField(default=False)),
                ('availability_pass', models.BooleanField(default=False)),
                ('isra_pass', models.BooleanField(default=False)),
                ('occupancy_pass', models.BooleanField(default=False)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('hard_fail_reasons', models.JSONField(blank=True, default=list)),
                ('admin_rationale', models.JSONField(blank=True, default=dict)),
                ('student_rationale', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-generated_at', 'rank', '-confidence_score'],
            },
        ),
        migrations.AddField(
            model_name='propmatchresult',
            name='hard_fail_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propmatchresult',
            name='rule_version',
            field=models.CharField(default='QM-Y1-1', max_length=30),
        ),
        migrations.AddField(
            model_name='propmatchresult',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propmatchresult',
            name='student_rationale',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='propmatchresult',
            index=models.Index(fields=['rule_version'], name='core_propma_rule_ve_eca3b1_idx'),
        ),
        migrations.AddField(
            model_name='propmatchscorehistory',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propmatch_score_history', to='core.property'),
        ),
        migrations.AddField(
            model_name='propmatchscorehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propmatch_score_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propmatchscorehistory',
            index=models.Index(fields=['user', 'generated_at'], name='core_propma_user_id_a5d0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='propmatchscorehistory',
            index=models.Index(fields=['property', 'generated_at'], name='core_propma_propert_e1c912_idx'),
        ),
        migrations.AddIndex(
            model_name='propmatchscorehistory',
            index=models.Index(fields=['rule_version'], name='core_propma_rule_ve_d5966e_idx'),
        ),
        migrations.AddIndex(
            model_name='propmatchscorehistory',
            index=models.Index(fields=['eligible'], name='core_propma_eligibl_d2717f_idx'),
        ),
    ]
