# Generated by Django 5.2.10 on 2026-05-29 17:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_propmatchscorehistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('APPLICATION_SUBMITTED', 'Application Submitted'), ('ENTRY_REVIEWED', 'Entry Reviewed'), ('VERIFICATION_READY', 'Verification Ready'), ('STAGE_CHANGED', 'Stage Changed'), ('MATCHING_STARTED', 'Matching Started'), ('PROPERTY_LOCKED', 'Property Locked'), ('MOVE_IN_SCHEDULED', 'Move-in Scheduled'), ('CARE_TICKET_OPENED', 'Care Ticket Opened'), ('SUPPORT_REQUEST_OPENED', 'Support Request Opened'), ('RENEWAL_REMINDER', 'Renewal Reminder'), ('COMPLETED', 'Completed')], default='STAGE_CHANGED', max_length=40)),
                ('from_stage', models.CharField(blank=True, max_length=30)),
                ('to_stage', models.CharField(blank=True, max_length=30)),
                ('student_message', models.CharField(max_length=240)),
                ('admin_message', models.CharField(blank=True, max_length=360)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='core.housingapplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.CharField(choices=[('STUDENT', 'Student'), ('LANDLORD', 'Landlord'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('message', models.CharField(max_length=360)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.housingapplication')),
                ('timeline_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.applicationtimelineevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='applicationtimelineevent',
            index=models.Index(fields=['application', 'created_at'], name='core_applic_applica_5ca653_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationtimelineevent',
            index=models.Index(fields=['event_type'], name='core_applic_event_t_368e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationtimelineevent',
            index=models.Index(fields=['to_stage'], name='core_applic_to_stag_9a1b58_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='core_notifi_user_id_bd2d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['application', 'created_at'], name='core_notifi_applica_353694_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['audience'], name='core_notifi_audienc_150fbf_idx'),
        ),
    ]
