# Generated by Django 5.2.10 on 2026-06-02 11:13

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_applicationtimelineevent_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancyhealthevent',
            name='event_type',
            field=models.CharField(choices=[('RENT_PAID_ON_TIME', 'Rent Paid On Time'), ('RENT_LATE', 'Rent Late'), ('COMPLAINT_RAISED', 'Complaint Raised'), ('COMPLAINT_RESOLVED', 'Complaint Resolved'), ('CARE_TICKET_OPENED', 'Care Ticket Opened'), ('CARE_TICKET_RESOLVED', 'Care Ticket Resolved'), ('ADMIN_NOTE', 'Admin Note')], max_length=40),
        ),
        migrations.CreateModel(
            name='CareTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('SAFETY', 'Safety'), ('ACCESS', 'Access'), ('UTILITIES', 'Utilities'), ('MOVE_IN', 'Move-in Issue'), ('PROPERTY_CARE', 'Property Care'), ('OTHER', 'Other')], default='MAINTENANCE', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned'), ('WAITING_LANDLORD', 'Waiting Landlord'), ('WAITING_TENANT', 'Waiting Tenant'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('student_safe_summary', models.CharField(blank=True, max_length=240)),
                ('landlord_visible', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_tickets', to='core.housingapplication')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_care_tickets', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_tickets', to='core.property')),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_tickets', to='core.tenancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareTicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=core.models.private_care_attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('landlord_visible', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.careticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareTicketEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('LANDLORD_UPDATED', 'Landlord Updated'), ('TENANT_UPDATED', 'Tenant Updated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='CREATED', max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('student_message', models.CharField(max_length=240)),
                ('landlord_message', models.CharField(blank=True, max_length=240)),
                ('admin_message', models.CharField(blank=True, max_length=360)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_ticket_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.careticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='careticket',
            index=models.Index(fields=['user', 'status'], name='core_careti_user_id_03721d_idx'),
        ),
        migrations.AddIndex(
            model_name='careticket',
            index=models.Index(fields=['property', 'status'], name='core_careti_propert_219f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='careticket',
            index=models.Index(fields=['tenancy', 'status'], name='core_careti_tenancy_2dfa22_idx'),
        ),
        migrations.AddIndex(
            model_name='careticket',
            index=models.Index(fields=['assigned_to', 'status'], name='core_careti_assigne_72ad77_idx'),
        ),
        migrations.AddIndex(
            model_name='careticket',
            index=models.Index(fields=['category', 'priority'], name='core_careti_categor_1d7153_idx'),
        ),
        migrations.AddIndex(
            model_name='careticket',
            index=models.Index(fields=['created_at'], name='core_careti_created_2f6d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='careticketattachment',
            index=models.Index(fields=['ticket'], name='core_careti_ticket__9710e4_idx'),
        ),
        migrations.AddIndex(
            model_name='careticketattachment',
            index=models.Index(fields=['uploaded_by'], name='core_careti_uploade_425691_idx'),
        ),
        migrations.AddIndex(
            model_name='careticketattachment',
            index=models.Index(fields=['uploaded_at'], name='core_careti_uploade_aa41f6_idx'),
        ),
        migrations.AddIndex(
            model_name='careticketevent',
            index=models.Index(fields=['ticket', 'created_at'], name='core_careti_ticket__0d691e_idx'),
        ),
        migrations.AddIndex(
            model_name='careticketevent',
            index=models.Index(fields=['event_type'], name='core_careti_event_t_d67d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='careticketevent',
            index=models.Index(fields=['to_status'], name='core_careti_to_stat_947fd3_idx'),
        ),
    ]
