# Generated by Django 5.2.10 on 2026-06-02 11:29

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_tenancyhealthevent_event_type_careticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('NHS_GUIDANCE', 'NHS Guidance'), ('BANKING_GUIDANCE', 'Banking Guidance'), ('ATS_CV_SUPPORT', 'ATS/CV Support'), ('AIRPORT_PICKUP', 'Airport Pickup'), ('SETTLEMENT_SUPPORT', 'Settlement Support'), ('UNIVERSITY_COMMUNITY', 'University/Community Guidance'), ('GENERAL_SUPPORT', 'General Support')], default='GENERAL_SUPPORT', max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned'), ('WAITING_STUDENT', 'Waiting Student'), ('WAITING_PARTNER', 'Waiting Partner'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('student_safe_summary', models.CharField(blank=True, max_length=240)),
                ('partner_visible', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='core.housingapplication')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportRequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=core.models.private_support_attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('partner_visible', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.supportrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_request_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportRequestEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('STUDENT_UPDATED', 'Student Updated'), ('PARTNER_UPDATED', 'Partner Updated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='CREATED', max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('student_message', models.CharField(max_length=240)),
                ('admin_message', models.CharField(blank=True, max_length=360)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_request_events', to=settings.AUTH_USER_MODEL)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.supportrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['user', 'status'], name='core_suppor_user_id_b5f507_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['application', 'status'], name='core_suppor_applica_3d89f0_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='core_suppor_assigne_8b17b4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['category', 'priority'], name='core_suppor_categor_b51da9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['created_at'], name='core_suppor_created_1610ad_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequestattachment',
            index=models.Index(fields=['support_request'], name='core_suppor_support_23389e_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequestattachment',
            index=models.Index(fields=['uploaded_by'], name='core_suppor_uploade_a936b9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequestattachment',
            index=models.Index(fields=['uploaded_at'], name='core_suppor_uploade_c40fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequestevent',
            index=models.Index(fields=['support_request', 'created_at'], name='core_suppor_support_8e3aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequestevent',
            index=models.Index(fields=['event_type'], name='core_suppor_event_t_59d90a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequestevent',
            index=models.Index(fields=['to_status'], name='core_suppor_to_stat_c0dbb2_idx'),
        ),
    ]
