# Generated by Django 5.2.10 on 2026-06-02 11:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_supportrequest_supportrequestattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('DOCUMENT_EXPIRY', 'Document Expiry'), ('MOVE_IN', 'Move-in'), ('RENT_DUE', 'Rent Due'), ('CARE_FOLLOW_UP', 'Care Follow-up'), ('SUPPORT_FOLLOW_UP', 'Support Follow-up'), ('RENEWAL', 'Renewal'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('COMPLETED', 'Completed'), ('DISMISSED', 'Dismissed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('student_message', models.CharField(max_length=240)),
                ('internal_notes', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_reminders', to='core.housingapplication')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assist_reminders', to=settings.AUTH_USER_MODEL)),
                ('care_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_reminders', to='core.careticket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assist_reminders', to=settings.AUTH_USER_MODEL)),
                ('support_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_reminders', to='core.supportrequest')),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_reminders', to='core.tenancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistAutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('DUE_PROCESSED', 'Due Processed'), ('NOTIFICATION_SENT', 'Notification Sent'), ('COMPLETED', 'Completed'), ('DISMISSED', 'Dismissed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('message', models.CharField(max_length=360)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_automation_logs', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='core.assistreminder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assistreminder',
            index=models.Index(fields=['user', 'status'], name='core_assist_user_id_97656b_idx'),
        ),
        migrations.AddIndex(
            model_name='assistreminder',
            index=models.Index(fields=['application', 'status'], name='core_assist_applica_dcbe20_idx'),
        ),
        migrations.AddIndex(
            model_name='assistreminder',
            index=models.Index(fields=['tenancy', 'status'], name='core_assist_tenancy_16af86_idx'),
        ),
        migrations.AddIndex(
            model_name='assistreminder',
            index=models.Index(fields=['assigned_to', 'status'], name='core_assist_assigne_2d48c8_idx'),
        ),
        migrations.AddIndex(
            model_name='assistreminder',
            index=models.Index(fields=['reminder_type', 'priority'], name='core_assist_reminde_d22693_idx'),
        ),
        migrations.AddIndex(
            model_name='assistreminder',
            index=models.Index(fields=['due_at', 'status'], name='core_assist_due_at_298c31_idx'),
        ),
        migrations.AddIndex(
            model_name='assistautomationlog',
            index=models.Index(fields=['reminder', 'created_at'], name='core_assist_reminde_df1ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='assistautomationlog',
            index=models.Index(fields=['action'], name='core_assist_action_120429_idx'),
        ),
    ]
