# Generated by Django 5.2.7 on 2026-06-10 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_assistreminder_assistautomationlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='retained_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['retained_until'], name='core_studen_retaine_03e2ca_idx'),
        ),
    ]
