# Generated by Django 5.1.15 on 2026-06-10 16:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_student_document_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending Approval')], default='PENDING', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agency_partners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(max_length=40, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('INTAKE', 'Intake Registered'), ('IN_PROGRESS', 'In Progress'), ('TENANCY_ACTIVE', 'Tenancy Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.agencypartner')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_referral', to='core.housingapplication')),
                ('student_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAYABLE', 'Payable'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payable_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commissions', to=settings.AUTH_USER_MODEL)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='core.agencyreferral')),
            ],
        ),
        migrations.AddIndex(
            model_name='agencypartner',
            index=models.Index(fields=['status'], name='core_agency_status_56c249_idx'),
        ),
        migrations.AddIndex(
            model_name='agencypartner',
            index=models.Index(fields=['created_at'], name='core_agency_created_79cf68_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyreferral',
            index=models.Index(fields=['agency', 'status'], name='core_agency_agency__396572_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyreferral',
            index=models.Index(fields=['referral_code'], name='core_agency_referra_9e1a68_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyreferral',
            index=models.Index(fields=['submitted_at'], name='core_agency_submitt_30c385_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['status'], name='core_referr_status_94b4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['created_at'], name='core_referr_created_7cef41_idx'),
        ),
    ]
