# Generated by Django 5.1.15 on 2026-06-10 16:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_agency_partner_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage', models.CharField(choices=[('INQUIRY', 'Inquiry'), ('VERIFY', 'Verify'), ('MATCH', 'Match'), ('ALLOCATE', 'Allocate'), ('CONTRACT', 'Contract'), ('ONBOARD', 'Onboard'), ('MOVE_IN', 'Move In'), ('ACTIVE', 'Active'), ('CARE', 'Care'), ('RENEWAL', 'Renewal'), ('EXIT', 'Exit')], default='INQUIRY', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('stage_entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agency_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_record', to='core.agencyreferral')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_record', to='core.housingapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_records', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_record', to='core.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(blank=True, choices=[('INQUIRY', 'Inquiry'), ('VERIFY', 'Verify'), ('MATCH', 'Match'), ('ALLOCATE', 'Allocate'), ('CONTRACT', 'Contract'), ('ONBOARD', 'Onboard'), ('MOVE_IN', 'Move In'), ('ACTIVE', 'Active'), ('CARE', 'Care'), ('RENEWAL', 'Renewal'), ('EXIT', 'Exit')], max_length=20)),
                ('to_stage', models.CharField(choices=[('INQUIRY', 'Inquiry'), ('VERIFY', 'Verify'), ('MATCH', 'Match'), ('ALLOCATE', 'Allocate'), ('CONTRACT', 'Contract'), ('ONBOARD', 'Onboard'), ('MOVE_IN', 'Move In'), ('ACTIVE', 'Active'), ('CARE', 'Care'), ('RENEWAL', 'Renewal'), ('EXIT', 'Exit')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.lifecyclerecord')),
            ],
        ),
        migrations.CreateModel(
            name='TenancyContractRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('right_to_rent_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('inventory_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('deposit_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_record', to='core.tenancy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contract_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('VERIFY_DOCUMENT', 'Verify Document'), ('CONFIRM_MATCH', 'Confirm Match'), ('ISSUE_CONTRACT', 'Issue Contract'), ('SCHEDULE_INSPECTION', 'Schedule Inspection'), ('RESOLVE_COMPLAINT', 'Resolve Complaint'), ('PROCESS_RENEWAL', 'Process Renewal'), ('REVIEW_HOLD', 'Review Booking Hold'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to='core.housingapplication')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to='core.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='AssistSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(choices=[('MATCH_PROPERTY', 'Match Property'), ('ESCALATE_COMPLAINT', 'Escalate Complaint'), ('SCHEDULE_RENEWAL', 'Schedule Renewal'), ('FLAG_RISK', 'Flag Risk'), ('SEND_REMINDER', 'Send Reminder'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_suggestions', to='core.housingapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_suggestions', to='core.tenancy')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='core_assist_status_d52e69_idx'), models.Index(fields=['suggestion_type'], name='core_assist_suggest_d5aa24_idx'), models.Index(fields=['created_at'], name='core_assist_created_1e7daa_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ADMIN_REVIEW', 'Admin Review'), ('APPROVED', 'Approved'), ('PROPERTY_RESERVED', 'Property Reserved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('student_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_holds', to='core.housingapplication')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_holds', to='core.property')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_booking_holds', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'status'], name='core_bookin_student_3cbb75_idx'), models.Index(fields=['property', 'status'], name='core_bookin_propert_07dfc6_idx'), models.Index(fields=['status'], name='core_bookin_status_3b5194_idx'), models.Index(fields=['expires_at'], name='core_bookin_expires_b390d1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lifecyclerecord',
            index=models.Index(fields=['student', 'current_stage'], name='core_lifecy_student_50570d_idx'),
        ),
        migrations.AddIndex(
            model_name='lifecyclerecord',
            index=models.Index(fields=['current_stage'], name='core_lifecy_current_367700_idx'),
        ),
        migrations.AddIndex(
            model_name='lifecyclerecord',
            index=models.Index(fields=['created_at'], name='core_lifecy_created_45d230_idx'),
        ),
        migrations.AddIndex(
            model_name='lifecycleevent',
            index=models.Index(fields=['record', 'created_at'], name='core_lifecy_record__5fc197_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancycontractrecord',
            index=models.Index(fields=['tenancy'], name='core_tenanc_tenancy_4d502d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['status', 'priority'], name='core_workfl_status_5f0b03_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['assigned_to', 'status'], name='core_workfl_assigne_51899f_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['due_date'], name='core_workfl_due_dat_59cfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['task_type'], name='core_workfl_task_ty_c54356_idx'),
        ),
    ]
