# Generated by Django 5.2.10 on 2026-02-01 06:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertySearchHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query_text', models.CharField(blank=True, max_length=300)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('sort', models.CharField(blank=True, max_length=60)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('results_count', models.IntegerField(default=0)),
                ('shown_property_ids', models.JSONField(blank=True, default=list)),
                ('total_pages', models.IntegerField(default=0)),
                ('clicked_property_id', models.UUIDField(blank=True, null=True)),
                ('enquiry_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_searches', to='analytics.visitorsession')),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('full_url', models.TextField(blank=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('page_type', models.CharField(choices=[('HOME', 'Home'), ('SEARCH', 'Search'), ('PROPERTY', 'Property Detail'), ('BLOG_LIST', 'Blog List'), ('BLOG_DETAIL', 'Blog Detail'), ('CONTACT', 'Contact'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('property_id', models.UUIDField(blank=True, null=True)),
                ('blog_post_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitorsession')),
            ],
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('PROPERTY_CARD_CLICK', 'Property Card Click'), ('PROPERTY_ENQUIRE_CLICK', 'Property Enquire Click'), ('BLOG_CARD_CLICK', 'Blog Card Click'), ('FILTER_APPLY', 'Filter Apply'), ('SORT_CHANGE', 'Sort Change'), ('NAV_CLICK', 'Nav Click'), ('CHATBOT_OPEN', 'Chatbot Open')], max_length=60)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('target_url', models.TextField(blank=True)),
                ('property_id', models.UUIDField(blank=True, null=True)),
                ('blog_post_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='analytics.visitorsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(default='web', max_length=30)),
                ('locale', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visitor_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='analytics.visitorsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('text', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=120)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extracted_filters', models.JSONField(blank=True, default=dict)),
                ('recommended_property_ids', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analytics.chatsession')),
                ('linked_property_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='analytics.propertysearchhistory')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='analytics_c_created_013dc0_idx'), models.Index(fields=['sender'], name='analytics_c_sender_f79ca9_idx'), models.Index(fields=['intent'], name='analytics_c_intent_c7dece_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['first_seen_at'], name='analytics_v_first_s_d8e3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['ip_address'], name='analytics_v_ip_addr_496ded_idx'),
        ),
        migrations.AddIndex(
            model_name='propertysearchhistory',
            index=models.Index(fields=['created_at'], name='analytics_p_created_732d87_idx'),
        ),
        migrations.AddIndex(
            model_name='propertysearchhistory',
            index=models.Index(fields=['results_count'], name='analytics_p_results_36a439_idx'),
        ),
        migrations.AddIndex(
            model_name='propertysearchhistory',
            index=models.Index(fields=['enquiry_submitted'], name='analytics_p_enquiry_641d60_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['created_at'], name='analytics_p_created_4c2b45_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page_type'], name='analytics_p_page_ty_5af892_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['path'], name='analytics_p_path_3382b5_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['created_at'], name='analytics_c_created_e826a5_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['event_type'], name='analytics_c_event_t_fb999a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['opened_at'], name='analytics_c_opened__224980_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['channel'], name='analytics_c_channel_f69c0b_idx'),
        ),
    ]
