# Generated by Django 5.2.7 on 2026-02-04 17:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('LANDLORD', 'Landlord'), ('STUDENT', 'Student')], help_text='Which role this question is for', max_length=20)),
                ('question_text', models.CharField(max_length=400)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['target_role', 'is_active', 'sort_order'], name='accounts_qu_target__7ec368_idx')],
            },
        ),
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_address', models.CharField(blank=True, max_length=300)),
                ('property_type', models.CharField(blank=True, max_length=80)),
                ('number_of_properties', models.CharField(blank=True, max_length=50)),
                ('bedrooms', models.CharField(blank=True, max_length=20)),
                ('current_status', models.CharField(blank=True, max_length=80)),
                ('expected_rent', models.CharField(blank=True, max_length=40)),
                ('services_required', models.CharField(blank=True, max_length=80)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='accounts_la_created_c5744d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.question')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='accounts_an_created_227a1c_idx'), models.Index(fields=['user'], name='accounts_an_user_id_c8871c_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('accommodation_type', models.CharField(blank=True, max_length=80)),
                ('budget', models.CharField(blank=True, max_length=80)),
                ('services_needed', models.CharField(blank=True, max_length=120)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='accounts_st_created_7c062c_idx')],
            },
        ),
    ]
