# Generated by Codex on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_passwordresetotp_delete_passwordresettoken_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="passwordresetotp",
            name="accounts_pa_otp_ccc55f_idx",
        ),
        migrations.RemoveField(
            model_name="passwordresetotp",
            name="otp",
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="otp_hash",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
