# Generated by Django 5.2.7 on 2026-06-10 16:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetotp_harden_otp_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataErasureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email_snapshot', models.EmailField(max_length=254)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ADMIN_REVIEW', 'Admin Review'), ('EXECUTED', 'Executed'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_erasure_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='accounts_da_status_8fcba8_idx'), models.Index(fields=['requested_at'], name='accounts_da_request_5c61b4_idx')],
            },
        ),
    ]
