from django.urls import path
from .views import *
from .admin_api import *
from .operational_api import (
    # BookingHold
    StudentBookingHoldCreateView,
    AdminBookingHoldListView,
    AdminBookingHoldActionView,
    # Contract record
    TenancyContractRecordView,
    # WorkflowTask
    WorkflowTaskListCreateView,
    WorkflowTaskDetailView,
    WorkflowTaskCompleteView,
    # LifecycleRecord
    AdminLifecycleRecordListView,
    AdminLifecycleRecordDetailView,
    AdminLifecycleAdvanceView,
    MyLifecycleRecordView,
    # AssistSuggestion
    AssistSuggestionListCreateView,
    AssistSuggestionReviewView,
)
from .agency_api import (
    AgencyPartnerListCreateView,
    AgencyPartnerDetailView,
    AgencyPartnerActivateView,
    AgencyReferralListCreateView,
    AgencyReferralDetailView,
    ReferralCommissionListView,
    ReferralCommissionMarkPayableView,
    ReferralCommissionMarkPaidView,
    AgencyDashboardView,
)

urlpatterns = [
    path("properties/public/", PublicPropertyListView.as_view(), name="public-properties"),
    path("health/", HealthCheckView.as_view(), name="health-check"),
    path("properties/public/<slug:slug>/", PublicPropertyDetailView.as_view(), name="public-property-detail"),
    # core/urls.py  (add under PUBLIC)
    path("contact/public/", PublicContactCreateView.as_view(), name="public-contact"),

    path("blog/public/", PublicBlogListView.as_view(), name="public-blog"),
    path("blog/public/<slug:slug>/", PublicBlogDetailView.as_view(), name="public-blog-detail"),
    path("me/intent/", MyIntentFormView.as_view(), name="my-intent"),
    path("me/isra/", MyISRAscoreView.as_view(), name="my-isra"),
    path("me/propmatch/", MyPropMatchView.as_view(), name="my-propmatch"),
    path("me/applications/", MyHousingApplicationListCreateView.as_view(), name="my-applications"),
    path("me/application-timeline/", MyApplicationTimelineListView.as_view(), name="my-application-timeline"),
    path("me/notifications/", MyNotificationListView.as_view(), name="my-notifications"),
    path("me/assist-reminders/", MyAssistReminderListView.as_view(), name="my-assist-reminders"),
    path("me/assist-reminders/<uuid:id>/complete/", MyAssistReminderCompleteView.as_view(), name="my-assist-reminder-complete"),
    path("me/tenancies/", MyTenancyListView.as_view(), name="my-tenancies"),
    path("me/rent-ledger/", MyRentLedgerListView.as_view(), name="my-rent-ledger"),
    path("me/tenancy-health/", MyTenancyHealthListView.as_view(), name="my-tenancy-health"),
    path("me/tenancy-records/", MyTenancyRecordListView.as_view(), name="my-tenancy-records"),
    path("tenancy-records/<uuid:id>/certificate/", TenancyRecordCertificateView.as_view(), name="tenancy-record-certificate"),
    path("me/tenancies/<uuid:id>/request-extension/", MyTenancyExtensionRequestView.as_view(), name="my-tenancy-extension"),
    path("me/complaints/", MyComplaintListCreateView.as_view(), name="my-complaints"),
    path("me/complaints/<uuid:id>/attachments/", MyComplaintAttachmentCreateView.as_view(), name="my-complaint-attachments"),
    path("me/care-tickets/", MyCareTicketListCreateView.as_view(), name="my-care-tickets"),
    path("me/care-tickets/<uuid:id>/attachments/", MyCareTicketAttachmentCreateView.as_view(), name="my-care-ticket-attachments"),
    path("me/support-requests/", MySupportRequestListCreateView.as_view(), name="my-support-requests"),
    path("me/support-requests/<uuid:id>/attachments/", MySupportRequestAttachmentCreateView.as_view(), name="my-support-request-attachments"),
    path("me/documents/", MyStudentDocumentListCreateView.as_view(), name="my-documents"),
    path("documents/<uuid:id>/download/", PrivateStudentDocumentDownloadView.as_view(), name="private-document-download"),
    path("complaint-attachments/<uuid:id>/download/", PrivateComplaintAttachmentDownloadView.as_view(), name="private-complaint-attachment-download"),
    path("care-attachments/<uuid:id>/download/", PrivateCareTicketAttachmentDownloadView.as_view(), name="private-care-attachment-download"),
    path("support-attachments/<uuid:id>/download/", PrivateSupportRequestAttachmentDownloadView.as_view(), name="private-support-attachment-download"),
    path("landlord/properties/", LandlordAssignedPropertyListView.as_view(), name="landlord-properties"),
    path("landlord/complaints/", LandlordComplaintListView.as_view(), name="landlord-complaints"),
    path("landlord/care-tickets/", LandlordCareTicketListView.as_view(), name="landlord-care-tickets"),
    path("landlord/yoe/", LandlordYOEMetricListView.as_view(), name="landlord-yoe"),
    path("landlord/rent-ledger/", LandlordRentLedgerListView.as_view(), name="landlord-rent-ledger"),
    path("landlord/isra-tiers/", LandlordISRATierListView.as_view(), name="landlord-isra-tiers"),
    path("landlord/enquiry-insights/", LandlordEnquiryInsightsView.as_view(), name="landlord-enquiry-insights"),

    path("properties/", AdminPropertyListCreateView.as_view(), name="admin-property-list-create"),
    path("properties/<uuid:id>/", AdminPropertyDetailView.as_view(), name="admin-property-detail"),
    path("property-images/", AdminPropertyImageListCreateView.as_view(), name="admin-property-image-list-create"),
    path("property-images/<int:id>/", AdminPropertyImageDetailView.as_view(), name="admin-property-image-detail"),
    path("property-videos/", AdminPropertyVideoListCreateView.as_view(), name="admin-property-video-list-create"),
    path("property-videos/<int:id>/", AdminPropertyVideoDetailView.as_view(), name="admin-property-video-detail"),
    path("blogs/", AdminBlogListCreateView.as_view(), name="admin-blog-list-create"),
    path("blogs/<uuid:id>/", AdminBlogDetailView.as_view(), name="admin-blog-detail"),
    path("intents/", AdminIntentFormListCreateView.as_view(), name="admin-intents"),
    path("intents/<uuid:id>/", AdminIntentFormDetailView.as_view(), name="admin-intent-detail"),
    path("isra-scores/", AdminISRAscoreListCreateView.as_view(), name="admin-isra-scores"),
    path("isra-scores/<uuid:id>/", AdminISRAscoreDetailView.as_view(), name="admin-isra-detail"),
    path("isra/run/<uuid:user_id>/", AdminRunISRAView.as_view(), name="admin-run-isra"),
    path("propmatch/run/<uuid:user_id>/", AdminRunPropMatchView.as_view(), name="admin-run-propmatch"),
    path("propmatch/results/", AdminPropMatchResultListView.as_view(), name="admin-propmatch-results"),
    path("propmatch/history/", AdminPropMatchScoreHistoryListView.as_view(), name="admin-propmatch-history"),
    path("applications/", AdminHousingApplicationListCreateView.as_view(), name="admin-applications"),
    path("applications/<uuid:id>/", AdminHousingApplicationDetailView.as_view(), name="admin-application-detail"),
    path("application-timeline/", AdminApplicationTimelineListView.as_view(), name="admin-application-timeline"),
    path("assist-reminders/", AdminAssistReminderListCreateView.as_view(), name="admin-assist-reminders"),
    path("assist-reminders/<uuid:id>/", AdminAssistReminderDetailView.as_view(), name="admin-assist-reminder-detail"),
    path("assist-reminders/process-due/", AdminRunAssistDueRemindersView.as_view(), name="admin-assist-process-due"),
    path("tenancies/", AdminTenancyListCreateView.as_view(), name="admin-tenancies"),
    path("tenancies/<uuid:id>/", AdminTenancyDetailView.as_view(), name="admin-tenancy-detail"),
    path("tenancy-health/", AdminTenancyHealthListView.as_view(), name="admin-tenancy-health"),
    path("tenancy-records/", AdminTenancyRecordListView.as_view(), name="admin-tenancy-records"),
    path("void-risk/", AdminVoidRiskListView.as_view(), name="admin-void-risk"),
    path("complaints/", AdminComplaintListCreateView.as_view(), name="admin-complaints"),
    path("complaints/<uuid:id>/", AdminComplaintDetailView.as_view(), name="admin-complaint-detail"),
    path("care-tickets/", AdminCareTicketListCreateView.as_view(), name="admin-care-tickets"),
    path("care-tickets/<uuid:id>/", AdminCareTicketDetailView.as_view(), name="admin-care-ticket-detail"),
    path("support-requests/", AdminSupportRequestListCreateView.as_view(), name="admin-support-requests"),
    path("support-requests/<uuid:id>/", AdminSupportRequestDetailView.as_view(), name="admin-support-request-detail"),
    path("support-intelligence/", AdminSupportIntelligenceView.as_view(), name="admin-support-intelligence"),
    path("documents/", AdminStudentDocumentListView.as_view(), name="admin-documents"),
    path("documents/<uuid:id>/", AdminStudentDocumentDetailView.as_view(), name="admin-document-detail"),
    path("complaint-attachments/", AdminComplaintAttachmentListView.as_view(), name="admin-complaint-attachments"),
    path("care-attachments/", AdminCareTicketAttachmentListView.as_view(), name="admin-care-attachments"),
    path("support-attachments/", AdminSupportRequestAttachmentListView.as_view(), name="admin-support-attachments"),
    path("expenses/", AdminPropertyExpenseListCreateView.as_view(), name="admin-expenses"),
    path("expenses/<uuid:id>/", AdminPropertyExpenseDetailView.as_view(), name="admin-expense-detail"),
    path("rent-ledger/", AdminRentLedgerListCreateView.as_view(), name="admin-rent-ledger"),
    path("rent-ledger/<uuid:id>/", AdminRentLedgerDetailView.as_view(), name="admin-rent-ledger-detail"),
    path("yoe-metrics/", AdminYOEMetricListView.as_view(), name="admin-yoe-metrics"),
    path("yoe-metrics/<uuid:id>/", AdminYOEMetricDetailView.as_view(), name="admin-yoe-metric-detail"),
    path("yoe/run/", AdminRunYOEView.as_view(), name="admin-run-yoe"),
    path("reports/production/", AdminProductionReportView.as_view(), name="admin-production-report"),
    path("monitoring/production/", AdminProductionMonitoringView.as_view(), name="admin-production-monitoring"),
    path("audit-logs/", AdminAuditLogListView.as_view(), name="admin-audit-logs"),

    # Agency Partner System
    path("agency/dashboard/", AgencyDashboardView.as_view(), name="agency-dashboard"),
    path("agency/partners/", AgencyPartnerListCreateView.as_view(), name="agency-partner-list"),
    path("agency/partners/<uuid:id>/", AgencyPartnerDetailView.as_view(), name="agency-partner-detail"),
    path("agency/partners/<uuid:id>/activate/", AgencyPartnerActivateView.as_view(), name="agency-partner-activate"),
    path("agency/referrals/", AgencyReferralListCreateView.as_view(), name="agency-referral-list"),
    path("agency/referrals/<uuid:id>/", AgencyReferralDetailView.as_view(), name="agency-referral-detail"),
    path("agency/commissions/", ReferralCommissionListView.as_view(), name="agency-commission-list"),
    path("agency/commissions/<uuid:id>/mark-payable/", ReferralCommissionMarkPayableView.as_view(), name="agency-commission-payable"),
    path("agency/commissions/<uuid:id>/mark-paid/", ReferralCommissionMarkPaidView.as_view(), name="agency-commission-paid"),

    # Booking Hold
    path("me/booking-holds/", StudentBookingHoldCreateView.as_view(), name="student-booking-holds"),
    path("booking-holds/", AdminBookingHoldListView.as_view(), name="admin-booking-holds"),
    path("booking-holds/<uuid:id>/<str:action>/", AdminBookingHoldActionView.as_view(), name="admin-booking-hold-action"),

    # Tenancy Contract Record
    path("tenancies/<uuid:tenancy_id>/contract/", TenancyContractRecordView.as_view(), name="tenancy-contract-record"),

    # Workflow Tasks
    path("workflow-tasks/", WorkflowTaskListCreateView.as_view(), name="workflow-task-list"),
    path("workflow-tasks/<uuid:id>/", WorkflowTaskDetailView.as_view(), name="workflow-task-detail"),
    path("workflow-tasks/<uuid:id>/complete/", WorkflowTaskCompleteView.as_view(), name="workflow-task-complete"),

    # Lifecycle Record
    path("me/lifecycle/", MyLifecycleRecordView.as_view(), name="my-lifecycle"),
    path("lifecycle/", AdminLifecycleRecordListView.as_view(), name="admin-lifecycle-list"),
    path("lifecycle/<uuid:id>/", AdminLifecycleRecordDetailView.as_view(), name="admin-lifecycle-detail"),
    path("lifecycle/<uuid:id>/advance/", AdminLifecycleAdvanceView.as_view(), name="admin-lifecycle-advance"),

    # Assist Suggestions
    path("assist-suggestions/", AssistSuggestionListCreateView.as_view(), name="assist-suggestion-list"),
    path("assist-suggestions/<uuid:id>/<str:action>/", AssistSuggestionReviewView.as_view(), name="assist-suggestion-review"),
]
