from django.urls import path
from .views import *
from .admin_api import *
urlpatterns = [
    path("properties/public/", PublicPropertyListView.as_view(), name="public-properties"),
    path("health/", HealthCheckView.as_view(), name="health-check"),
    path("properties/public/<slug:slug>/", PublicPropertyDetailView.as_view(), name="public-property-detail"),
    # core/urls.py  (add under PUBLIC)
    path("contact/public/", PublicContactCreateView.as_view(), name="public-contact"),

    path("blog/public/", PublicBlogListView.as_view(), name="public-blog"),
    path("blog/public/<slug:slug>/", PublicBlogDetailView.as_view(), name="public-blog-detail"),
    path("me/intent/", MyIntentFormView.as_view(), name="my-intent"),
    path("me/isra/", MyISRAscoreView.as_view(), name="my-isra"),
    path("me/propmatch/", MyPropMatchView.as_view(), name="my-propmatch"),
    path("me/applications/", MyHousingApplicationListCreateView.as_view(), name="my-applications"),
    path("me/tenancies/", MyTenancyListView.as_view(), name="my-tenancies"),
    path("me/rent-ledger/", MyRentLedgerListView.as_view(), name="my-rent-ledger"),
    path("me/tenancy-health/", MyTenancyHealthListView.as_view(), name="my-tenancy-health"),
    path("me/tenancy-records/", MyTenancyRecordListView.as_view(), name="my-tenancy-records"),
    path("tenancy-records/<uuid:id>/certificate/", TenancyRecordCertificateView.as_view(), name="tenancy-record-certificate"),
    path("me/tenancies/<uuid:id>/request-extension/", MyTenancyExtensionRequestView.as_view(), name="my-tenancy-extension"),
    path("me/complaints/", MyComplaintListCreateView.as_view(), name="my-complaints"),
    path("me/complaints/<uuid:id>/attachments/", MyComplaintAttachmentCreateView.as_view(), name="my-complaint-attachments"),
    path("me/documents/", MyStudentDocumentListCreateView.as_view(), name="my-documents"),
    path("documents/<uuid:id>/download/", PrivateStudentDocumentDownloadView.as_view(), name="private-document-download"),
    path("complaint-attachments/<uuid:id>/download/", PrivateComplaintAttachmentDownloadView.as_view(), name="private-complaint-attachment-download"),
    path("landlord/properties/", LandlordAssignedPropertyListView.as_view(), name="landlord-properties"),
    path("landlord/complaints/", LandlordComplaintListView.as_view(), name="landlord-complaints"),
    path("landlord/yoe/", LandlordYOEMetricListView.as_view(), name="landlord-yoe"),
    path("landlord/rent-ledger/", LandlordRentLedgerListView.as_view(), name="landlord-rent-ledger"),
    path("landlord/isra-tiers/", LandlordISRATierListView.as_view(), name="landlord-isra-tiers"),

    path("properties/", AdminPropertyListCreateView.as_view(), name="admin-property-list-create"),
    path("properties/<uuid:id>/", AdminPropertyDetailView.as_view(), name="admin-property-detail"),
    path("property-images/", AdminPropertyImageListCreateView.as_view(), name="admin-property-image-list-create"),
    path("property-images/<int:id>/", AdminPropertyImageDetailView.as_view(), name="admin-property-image-detail"),
    path("property-videos/", AdminPropertyVideoListCreateView.as_view(), name="admin-property-video-list-create"),
    path("property-videos/<int:id>/", AdminPropertyVideoDetailView.as_view(), name="admin-property-video-detail"),
    path("blogs/", AdminBlogListCreateView.as_view(), name="admin-blog-list-create"),
    path("blogs/<uuid:id>/", AdminBlogDetailView.as_view(), name="admin-blog-detail"),
    path("intents/", AdminIntentFormListCreateView.as_view(), name="admin-intents"),
    path("intents/<uuid:id>/", AdminIntentFormDetailView.as_view(), name="admin-intent-detail"),
    path("isra-scores/", AdminISRAscoreListCreateView.as_view(), name="admin-isra-scores"),
    path("isra-scores/<uuid:id>/", AdminISRAscoreDetailView.as_view(), name="admin-isra-detail"),
    path("isra/run/<uuid:user_id>/", AdminRunISRAView.as_view(), name="admin-run-isra"),
    path("propmatch/run/<uuid:user_id>/", AdminRunPropMatchView.as_view(), name="admin-run-propmatch"),
    path("propmatch/results/", AdminPropMatchResultListView.as_view(), name="admin-propmatch-results"),
    path("applications/", AdminHousingApplicationListCreateView.as_view(), name="admin-applications"),
    path("applications/<uuid:id>/", AdminHousingApplicationDetailView.as_view(), name="admin-application-detail"),
    path("tenancies/", AdminTenancyListCreateView.as_view(), name="admin-tenancies"),
    path("tenancies/<uuid:id>/", AdminTenancyDetailView.as_view(), name="admin-tenancy-detail"),
    path("tenancy-health/", AdminTenancyHealthListView.as_view(), name="admin-tenancy-health"),
    path("tenancy-records/", AdminTenancyRecordListView.as_view(), name="admin-tenancy-records"),
    path("void-risk/", AdminVoidRiskListView.as_view(), name="admin-void-risk"),
    path("complaints/", AdminComplaintListCreateView.as_view(), name="admin-complaints"),
    path("complaints/<uuid:id>/", AdminComplaintDetailView.as_view(), name="admin-complaint-detail"),
    path("documents/", AdminStudentDocumentListView.as_view(), name="admin-documents"),
    path("documents/<uuid:id>/", AdminStudentDocumentDetailView.as_view(), name="admin-document-detail"),
    path("complaint-attachments/", AdminComplaintAttachmentListView.as_view(), name="admin-complaint-attachments"),
    path("expenses/", AdminPropertyExpenseListCreateView.as_view(), name="admin-expenses"),
    path("expenses/<uuid:id>/", AdminPropertyExpenseDetailView.as_view(), name="admin-expense-detail"),
    path("rent-ledger/", AdminRentLedgerListCreateView.as_view(), name="admin-rent-ledger"),
    path("rent-ledger/<uuid:id>/", AdminRentLedgerDetailView.as_view(), name="admin-rent-ledger-detail"),
    path("yoe-metrics/", AdminYOEMetricListView.as_view(), name="admin-yoe-metrics"),
    path("yoe-metrics/<uuid:id>/", AdminYOEMetricDetailView.as_view(), name="admin-yoe-metric-detail"),
    path("yoe/run/", AdminRunYOEView.as_view(), name="admin-run-yoe"),
    path("audit-logs/", AdminAuditLogListView.as_view(), name="admin-audit-logs"),
]
